servernode:
    build: .
    links:
        - db
    ports: 
        - "8001:8000"
    environment:
        NODE_ENV: development

db:
    image: mariadb
    # restart: always
    ports: 
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 12345